<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="0"
            failures="0"
            tests="0">

  <testsuite name="demo"
    errors="0" failures="0" hostname="" id="" package="demo" skipped="2"
    tests="0" time="0" timestamp="">
  

  
    <system-err>
        Error: An error occurred while retrieving a new session: &#34;Connection refused to 192.168.64.3:4444&#34;. If the Webdriver/Selenium service is managed by Nightwatch, check if &#34;start_process&#34; is set to &#34;true&#34;.
       at HttpRequest.emit (node:events:379:20)
       at ClientRequest.emit (node:events:391:22)
       at Socket.socketErrorListener (node:_http_client:462:9)
       at Socket.emit (node:events:379:20)
       at emitErrorNT (node:internal/streams/destroy:188:8)
       at emitErrorCloseNT (node:internal/streams/destroy:153:3)
       at processTicksAndRejections (node:internal/process/task_queues:81:21)
    </system-err>
  

    
    <error message="An error occurred while retrieving a new session: &#34;Connection refused to 192.168.64.3:4444&#34;. If the Webdriver/Selenium service is managed by Nightwatch, check if &#34;start_process&#34; is set to &#34;true&#34;."><![CDATA[
      Error: An error occurred while retrieving a new session: &#34;Connection refused to 192.168.64.3:4444&#34;. If the Webdriver/Selenium service is managed by Nightwatch, check if &#34;start_process&#34; is set to &#34;true&#34;.
    at Selenium2Protocol.handleSessionCreateError (/home/node/app/node_modules/nightwatch/lib/transport/transport.js:103:15)
    at HttpRequest.&lt;anonymous&gt; (/home/node/app/node_modules/nightwatch/lib/transport/transport.js:159:32)
    at HttpRequest.emit (node:events:379:20)
    at ClientRequest.&lt;anonymous&gt; (/home/node/app/node_modules/nightwatch/lib/http/request.js:142:19)
    at ClientRequest.emit (node:events:391:22)
    at Socket.socketErrorListener (node:_http_client:462:9)
    at Socket.emit (node:events:379:20)
    at emitErrorNT (node:internal/streams/destroy:188:8)
    at emitErrorCloseNT (node:internal/streams/destroy:153:3)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)
      ]]></error>  

  
    
    <testcase
      name="step one: navigate to google" classname="demo">
      <skipped />
    </testcase>
    
    <testcase
      name="step two: click input" classname="demo">
      <skipped />
    </testcase>
    
  
  </testsuite>
</testsuites>
